name: Build and deploy Next.js SSR app to Azure Web App - daynightcricket-prod

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: |
          npm install

      - name: Build the app
        run: |
          npm run build  # Ensure Next.js build command is run

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-app
          path: .next

  deploy:
    runs-on: windows-latest  # Using Windows runner for deployment to a Windows-based App Service
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: nextjs-app

      - name: Set up Node.js for deployment
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies for production
        run: |
          npm ci  # For clean installation without package-lock modification

      - name: Use xcopy to copy static files
        run: |
          xcopy /E /I .next\standalone\* build\
          xcopy /E /I .next\static build\.next\static
          xcopy /E /I public build\public

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'daynightcricket-prod'
          slot-name: 'Production'
          package: ./build  # Path to the root of the app for deployment
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_3FC52D650F27479DAAFDFAC542EDCF00 }}

      - name: Start the Next.js SSR app on Azure
        run: |
          npm run start  # This will start the Next.js app in production mode (using .next/standalone/server.js)

